Repository percolate/charlatan, pull requests merged in 2018-04, with the labels that each got.

#17 Add Blog Post Link to README
  README.md
Labels: documentation

#18 Generate Helpers to Automate Stub Usage
  .circleci/config.yml
  VERSION.txt
  generator.go
  template.go
  testdata/array/array.go
  testdata/channeler/channeler.go
  testdata/embedder/embedder.go
  testdata/funcer/funcer.go
  testdata/importer/importer.go
  testdata/interfacer/interfacer.go
  testdata/mapper/mapper.go
  testdata/multireturner/multireturner.go
  testdata/namedvaluer/namedvaluer.go
  testdata/pointer/pointer.go
  testdata/qualifier/qualifier.go
  testdata/structer/structer.go
Labels: enhancement

#19 Fix formatting related to variadic types
  VERSION.txt
  model.go
  template.go
Labels: bug

#24 Fix README Typos
  README.md
Labels: bug, documentation
